name: stream_watcher
description: An extension for watching Dart streams, allowing a stream to be "converted" to a value by simply calling `.watch(context)`.
version: 0.1.2-nullsafety.1
homepage: https://github.com/davystrong

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3