name: stream_watcher
description: Extension for watching streams.
version: 0.0.1
author: David Armstrong
homepage: https://github.com/davystrong

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3