name: basic-tests

on:
  push

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@master
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter test